name: Build and Compile Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install

      - name: Build project
        run: |
          npm run build

      - name: Verify presence of package.json
        run: |
          ls -alh  # Liste les fichiers pour vérifier la présence de package.json à la racine

      - name: Create release directory and add files
        run: |
          mkdir release
          cp -r build/* release/
          cp package.json release/  # Copier package.json dans le dossier release
          
      - name: Verify files in release directory
        run: |
          ls -alh release  # Vérifie que package.json et les fichiers build sont bien dans le dossier release

      - name: Create tar.gz archive
        run: |
          tar -czf release.tar.gz -C release .  # Crée l'archive tar.gz

      - name: Upload compiled files as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: compiled-files
          path: release.tar.gz  # Télécharge l'archive tar.gz comme artefact

      - name: Create GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: release.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
