name: Build and Compile Project

on:
  push:
    branches:
      - master    # ou la branche de votre choix
  release:
    types:
      - created   # Se déclenche lors de la création d'un release

jobs:
  build:
    runs-on: ubuntu-latest  # Utilisation d'une machine Ubuntu pour l'exécution

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Récupère le code source du dépôt

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Configure Node.js pour l'environnement GitHub Actions
        with:
          node-version: '16'  # Remplacez par la version de Node.js que vous utilisez

      - name: Install dependencies
        run: |
          npm install  # Installe les dépendances du projet

      - name: Build project
        run: |
          npm run build  # Compile le projet

      - name: Upload compiled files as artifacts
        uses: actions/upload-artifact@v3  # Télécharge les fichiers compilés comme artefacts
        with:
          name: compiled-files
          path: build/  # Le répertoire contenant les fichiers compilés
