name: Build and Publish Release

on:
  push:
    tags:
      - 'v*'  # Déclenche l'action sur tous les tags commençant par 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Archive compiled files
        run: |
          mkdir release
          cp -r build/* release/
          tar -czf release.tar.gz -C release .

      - name: Push tag (if not already pushed)
        run: |
          TAG_NAME="v$(date +'%Y.%m.%d.%H%M%S')"
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release.tar.gz  # Fichier que vous souhaitez ajouter à la release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Le token d'authentification GitHub
